name = "rnf-api-proxy"
type = "javascript"

account_id = ""
workers_dev = true
routes = ["www.routenotfound.com/api/*", "routenotfound.com/api/*"]
zone_id = "cb2e7aac346593483a4e3a8543cb6855"

# Secrets
# SERVICE_HOST
